require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe OkrsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Okr. As you add validations to Okr, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # OkrsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all okrs as @okrs" do
      okr = Okr.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(assigns(:okrs)).to eq([okr])
    end
  end

  describe "GET #show" do
    it "assigns the requested okr as @okr" do
      okr = Okr.create! valid_attributes
      get :show, params: {id: okr.to_param}, session: valid_session
      expect(assigns(:okr)).to eq(okr)
    end
  end

  describe "GET #new" do
    it "assigns a new okr as @okr" do
      get :new, params: {}, session: valid_session
      expect(assigns(:okr)).to be_a_new(Okr)
    end
  end

  describe "GET #edit" do
    it "assigns the requested okr as @okr" do
      okr = Okr.create! valid_attributes
      get :edit, params: {id: okr.to_param}, session: valid_session
      expect(assigns(:okr)).to eq(okr)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Okr" do
        expect {
          post :create, params: {okr: valid_attributes}, session: valid_session
        }.to change(Okr, :count).by(1)
      end

      it "assigns a newly created okr as @okr" do
        post :create, params: {okr: valid_attributes}, session: valid_session
        expect(assigns(:okr)).to be_a(Okr)
        expect(assigns(:okr)).to be_persisted
      end

      it "redirects to the created okr" do
        post :create, params: {okr: valid_attributes}, session: valid_session
        expect(response).to redirect_to(Okr.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved okr as @okr" do
        post :create, params: {okr: invalid_attributes}, session: valid_session
        expect(assigns(:okr)).to be_a_new(Okr)
      end

      it "re-renders the 'new' template" do
        post :create, params: {okr: invalid_attributes}, session: valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested okr" do
        okr = Okr.create! valid_attributes
        put :update, params: {id: okr.to_param, okr: new_attributes}, session: valid_session
        okr.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested okr as @okr" do
        okr = Okr.create! valid_attributes
        put :update, params: {id: okr.to_param, okr: valid_attributes}, session: valid_session
        expect(assigns(:okr)).to eq(okr)
      end

      it "redirects to the okr" do
        okr = Okr.create! valid_attributes
        put :update, params: {id: okr.to_param, okr: valid_attributes}, session: valid_session
        expect(response).to redirect_to(okr)
      end
    end

    context "with invalid params" do
      it "assigns the okr as @okr" do
        okr = Okr.create! valid_attributes
        put :update, params: {id: okr.to_param, okr: invalid_attributes}, session: valid_session
        expect(assigns(:okr)).to eq(okr)
      end

      it "re-renders the 'edit' template" do
        okr = Okr.create! valid_attributes
        put :update, params: {id: okr.to_param, okr: invalid_attributes}, session: valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested okr" do
      okr = Okr.create! valid_attributes
      expect {
        delete :destroy, params: {id: okr.to_param}, session: valid_session
      }.to change(Okr, :count).by(-1)
    end

    it "redirects to the okrs list" do
      okr = Okr.create! valid_attributes
      delete :destroy, params: {id: okr.to_param}, session: valid_session
      expect(response).to redirect_to(okrs_url)
    end
  end

end
